name: CI

on:
  pull_request:
    branches: [main, improvements]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip CI for draft PRs
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        node-version: [
          # 18.x, 
          20.x
        ]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run buildpack
      # Remove pnpm-lock.yaml to force a clean install, 
      # otherwise the tarball sha will be different and this will fail.
      - run: cd examples/vitest && rm -rf pnpm-lock.yaml && pnpm install --force
      - run: pnpm run lint
      - run: pnpm test
